import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('claims')
export class Claim {
  @PrimaryGeneratedColumn('increment', { type: 'bigint' }) id!: number;
  @Column({ nullable: true }) ClaimNumber!: string;
  @Column({ nullable: true }) ProposalNumber!: string;
  @Column({ nullable: true }) PolicyNumber!: string;
  @Column({ nullable: true }) ArchiveNumber!: string;
  @Column({ nullable: true }) OfficePremium!: string;
  @Column({ nullable: true }) PremiumFrequency!: string;
  @Column({ type: 'date', nullable: true }) ClaimDate!: string;
  @Column({ nullable: true }) SubscriberNumber!: string;
  @Column({ nullable: true }) SubscriberName!: string;
  @Column({ nullable: true }) SubscriberID!: string;
  @Column({ nullable: true }) PhoneNumber!: string;
  @Column({ nullable: true }) AgentCode!: string;
  @Column({ nullable: true }) AgentName!: string;
  @Column({ nullable: true }) Product!: string;
  @Column({ nullable: true }) Branch!: string;
  @Column({ nullable: true }) RequestID!: string;
  @Column({ type: 'date', nullable: true }) RequestDate!: string;
  @Column({ nullable: true }) RequestReceiver!: string;
  @Column({ type: 'numeric', nullable: true }) ReserveAmount!: number;
  @Column({ type: 'numeric', nullable: true }) TotalPremiumPaid!: number;
  @Column({ type: 'numeric', nullable: true }) TotalFees!: number;
  @Column({ type: 'numeric', nullable: true }) TotalInvestedPremium!: number;
  @Column({ type: 'numeric', nullable: true }) TotalInterest!: number;
  @Column({ type: 'numeric', nullable: true }) TotalWithdrawal!: number;
  @Column({ type: 'numeric', nullable: true }) TotalPenalty!: number;
  @Column({ type: 'numeric', nullable: true }) TotalAmountToPay!: number;
  @Column({ type: 'date', nullable: true }) EventDate!: string;
  @Column({ type: 'date', nullable: true }) DeclarationDate!: string;
  @Column({ nullable: true }) ClaimStatus!: string;
  @Column({ nullable: true }) ClaimDescription!: string;
  @Column({ nullable: true }) Claimant!: string;
  @Column({ nullable: true }) ClaimType!: string;
  @Column({ type: 'date', nullable: true }) PaymentDate!: string;
  @Column({ type: 'numeric', nullable: true }) AmountPaid!: number;
  @Column({ nullable: true }) RequisitionNumber!: string;
  @Column({ nullable: true }) RequisitionAuthorized!: string;
  @Column({ nullable: true }) RequisitionApproved!: string;
  @Column({ nullable: true }) RequisitionFunded!: string;
  @Column({ nullable: true }) RequisitionPosted!: string;
  @Column({ nullable: true }) Initiator!: string;
  @Column({ nullable: true }) Authorizer!: string;
  @Column({ nullable: true }) Approver!: string;
  @Column({ name: 'created_at', type: 'timestamp', nullable: true }) CreatedAt!: Date;
  @Column({ name: 'updated_at', type: 'timestamp', nullable: true }) UpdatedAt!: Date;
}
