import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('policies')
export class Policy {
  @PrimaryGeneratedColumn('increment', { type: 'bigint' }) id!: number;
  @Column({ name: 'proposal_number', nullable: true }) ProposalNumber!: string;
  @Column({ name: 'policy_number', nullable: true }) PolicyNumber!: string;
  @Column({ name: 'archive_number', nullable: true }) ArchiveNumber!: string;
  @Column({ name: 'product_code', nullable: true }) ProductCode!: string;
  @Column({ name: 'product_name', nullable: true }) ProductName!: string;
  @Column({ name: 'agent_code', nullable: true }) AgentCode!: string;
  @Column({ name: 'agent_name', nullable: true }) AgentName!: string;
  @Column({ name: 'agent_type', nullable: true }) AgentType!: string;
  @Column({ name: 'effective_date', type: 'date', nullable: true }) EffectiveDate!: string;
  @Column({ type: 'numeric', nullable: true }) Premium!: number;
  @Column({ name: 'payment_frequency', nullable: true }) PaymentFrequency!: string;
  @Column({ name: 'benefit_frequency', nullable: true }) BenefitFrequency!: string;
  @Column({ name: 'contract_duration', type: 'int', nullable: true }) ContractDuration!: number;
  @Column({ name: 'benefit_duration', type: 'int', nullable: true }) BenefitDuration!: number;
  @Column({ name: 'retirement_age', type: 'int', nullable: true }) RetirementAge!: number;
  @Column({ name: 'expiry_date', type: 'date', nullable: true }) ExpiryDate!: string;
  @Column({ name: 'last_payment_date', type: 'date', nullable: true }) LastPaymentDate!: string;
  @Column({ name: 'sum_assured', type: 'numeric', nullable: true }) SumAssured!: number;
  @Column({ name: 'death_benefit', type: 'numeric', nullable: true }) DeathBenefit!: number;
  @Column({ name: 'death_cover', type: 'numeric', nullable: true }) DeathCover!: number;
  @Column({ nullable: true }) Status!: string;
  @Column({ name: 'status_date', type: 'date', nullable: true }) StatusDate!: string;
  @Column({ name: 'life_premium', type: 'numeric', nullable: true }) LifePremium!: number;
  @Column({ name: 'annual_premium', type: 'numeric', nullable: true }) AnnualPremium!: number;
  @Column({ name: 'annual_life_premium', type: 'numeric', nullable: true }) AnnualLifePremium!: number;
  @Column({ name: 'subscriber_number', nullable: true }) SubscriberNumber!: string;
  @Column({ name: 'subscriber_name', nullable: true }) SubscriberName!: string;
  @Column({ name: 'id_type', nullable: true }) IDType!: string;
  @Column({ name: 'id_number', nullable: true }) IDNumber!: string;
  @Column({ name: 'date_of_birth', type: 'date', nullable: true }) DateOfBirth!: string;
  @Column({ name: 'place_of_birth', nullable: true }) PlaceOfBirth!: string;
  @Column({ nullable: true }) Gender!: string;
  @Column({ name: 'marital_status', nullable: true }) MaritalStatus!: string;
  @Column({ nullable: true }) Nationality!: string;
  @Column({ nullable: true }) Telephone!: string;
  @Column({ nullable: true }) Email!: string;
  @Column({ nullable: true }) Beneficiary!: string;
  @Column({ nullable: true }) District!: string;
  @Column({ nullable: true }) Sector!: string;
  @Column({ name: 'staff_number', nullable: true }) StaffNumber!: string;
  @Column({ nullable: true }) Employer!: string;
  @Column({ nullable: true }) Branch!: string;
  @Column({ name: 'total_premium_paid', type: 'numeric', nullable: true }) TotalPremiumPaid!: number;
  @Column({ name: 'total_pure_premium', type: 'numeric', nullable: true }) TotalPurePremium!: number;
  @Column({ name: 'total_management_fee', type: 'numeric', nullable: true }) TotalManagementFee!: number;
  @Column({ name: 'total_acquisition_fee', type: 'numeric', nullable: true }) TotalAcquisitionFee!: number;
  @Column({ name: 'total_instalment_fee', type: 'numeric', nullable: true }) TotalInstalmentFee!: number;
  @Column({ name: 'total_life_premium', type: 'numeric', nullable: true }) TotalLifePremium!: number;
  @Column({ name: 'total_premium_expected', type: 'numeric', nullable: true }) TotalPremiumExpected!: number;
  @Column({ name: 'date_lapsed', type: 'date', nullable: true }) DateLapsed!: string;
  @Column({ name: 'date_paid_up', type: 'date', nullable: true }) DatePaidUp!: string;
  @Column({ name: 'created_at', type: 'timestamp', nullable: true }) CreatedAt!: Date;
  @Column({ name: 'updated_at', type: 'timestamp', nullable: true }) UpdatedAt!: Date;
}
