import { Entity, Column, PrimaryColumn } from 'typeorm';

@Entity('proposals')
export class Proposal {
  @PrimaryColumn('int') ID!: number;
  @Column({ nullable: true }) ProposalNumber!: string;
  @Column({ nullable: true }) Status!: string;
  @Column({ nullable: true }) FirstName!: string;
  @Column({ nullable: true }) Surname!: string;
  @Column({ nullable: true }) Gender!: string;
  @Column({ nullable: true }) CustomerIDPassport!: string;
  @Column({ nullable: true }) Nationality!: string;
  @Column({ nullable: true }) PolicyHolderName!: string;
  @Column({ nullable: true }) PolicyHolderPhone!: string;
  @Column({ nullable: true }) PolicyHolderEmail!: string;
  @Column({ nullable: true }) PolicyHolderID!: string;
  @Column({ nullable: true }) PolicyHolderRelationship!: string;
  @Column({ nullable: true }) ProductType!: string;
  @Column('float', { nullable: true }) PremiumAmount!: number;
  @Column({ nullable: true }) PaymentFrequency!: string;
  @Column({ nullable: true }) ProposedEffectiveDate!: string;
  @Column({ nullable: true }) PolicyDuration!: string;
  @Column({ nullable: true }) BankName!: string;
  @Column({ nullable: true }) AccountNumber!: string;
  @Column({ nullable: true }) PremiumPaymentOption!: string;
  @Column({ nullable: true }) StandingOrderSubmissionDate!: string;
  @Column({ nullable: true }) OVPAPSSStatus!: string;
  @Column({ nullable: true }) Employer!: string;
  @Column({ nullable: true }) OtherInsured!: string;
  @Column({ nullable: true }) NextOfKinName!: string;
  @Column({ nullable: true }) NextOfKinID!: string;
  @Column({ nullable: true }) NextOfKinPhone!: string;
  @Column({ nullable: true }) NextOfKinEmail!: string;
  @Column({ nullable: true }) NextOfKinRelationship!: string;
  @Column({ nullable: true }) ChildEducation!: string;
  @Column({ nullable: true }) ChildBirthDate!: string;
  @Column({ nullable: true }) AgentBrokerStaffName!: string;
  @Column({ nullable: true }) AgentName!: string;
  @Column({ nullable: true }) AgentBrokerStaffCode!: string;
  @Column({ nullable: true }) RelationshipOfficer!: string;
  @Column({ nullable: true }) StaffNameDirectBusiness!: string;
  @Column({ nullable: true }) Signature!: string;
  @Column({ nullable: true }) Created!: string;
  @Column({ nullable: true }) SubmissionDate!: string;
  @Column({ nullable: true }) CreatedBy!: string;
  @Column({ nullable: true }) Modified!: string;
  @Column({ nullable: true }) ModifiedBy!: string;
  @Column({ nullable: true }) CommentsNotes!: string;
  @Column('int', { nullable: true }) Version!: number;
  @Column({ nullable: true }) DateSentToUnderwritingByRetail!: string;
  @Column({ nullable: true }) DateSentToFinanceByUnderwriting!: string;
  @Column({ nullable: true }) FirstDeductionSubmissionDate!: string;
  @Column({ nullable: true }) DateOfFirstPremium!: string;
  @Column({ nullable: true }) PostingDateOfContractProduction!: string;
  @Column({ nullable: true }) DateOfContractReceptionByRetail!: string;
  @Column({ nullable: true }) DateOfContractDistributionFromRetailToAgent!: string;
  @Column({ nullable: true }) AgentStaffGivenContract!: string;
  @Column({ nullable: true }) DateSignedContractReturned!: string;
  @Column({ nullable: true }) ProposalDeductionStatusComments!: string;
}
